# Generated by Django 5.2.6 on 2025-09-24 12:19

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('authors', models.ManyToManyField(to='review.author')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=2000)),
                ('rating', models.DecimalField(choices=[(Decimal('0.0'), '0.0 stars'), (Decimal('0.5'), '0.5 stars'), (Decimal('1.0'), '1.0 stars'), (Decimal('1.5'), '1.5 stars'), (Decimal('2.0'), '2.0 stars'), (Decimal('2.5'), '2.5 stars'), (Decimal('3.0'), '3.0 stars'), (Decimal('3.5'), '3.5 stars'), (Decimal('4.0'), '4.0 stars'), (Decimal('4.5'), '4.5 stars'), (Decimal('5.0'), '5.0 stars')], decimal_places=1, max_digits=2)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='review.book')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_on'],
                'constraints': [models.UniqueConstraint(fields=('reviewer', 'book'), name='unique_user_review_for_book')],
            },
        ),
    ]
