# Generated by Django 5.2.6 on 2025-10-10 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='content_preview',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
