# Generated by Django 5.2.6 on 2025-10-10 13:13

from django.db import migrations


def populate_content_preview(apps, schema_editor):
    Review = apps.get_model('review', 'Review')
    for review in Review.objects.all():
        review.content_preview = review.content[:200]
        review.save()


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0002_review_content_preview'),
    ]

    operations = [
        migrations.RunPython(populate_content_preview),
    ]
